const TEAM_NAMES=['Mumbai Indians','Chennai Super Kings','Royal Challengers Bengaluru','Kolkata Knight Riders','Rajasthan Royals','Sunrisers Hyderabad','Delhi Capitals','Punjab Kings'];
const TEAM_CODES=['MI','CSK','RCB','KKR','RR','SRH','DC','PBKS'];
const state={room:null,isHost:false,name:'',team:null,peer:null,connections:[],players:{},teams:{},current:null,lot:0,timer:null,timeLeft:30,queue:[],queueIndex:0};
const $=id=>document.getElementById(id);const money=n=>`₹${Number(n).toFixed(2)} Cr`;
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2200)}
function log(t){const d=document.createElement('div');d.className='log-item';d.innerHTML=t;$('activityLog').prepend(d)}
function makeTeams(){state.teams={};TEAM_NAMES.forEach((name,i)=>state.teams[TEAM_CODES[i]]={name,owner:null,budget:100,players:[]})}
function renderTeams(){const box=$('teamsList');box.innerHTML='';Object.entries(state.teams).forEach(([code,t])=>{const d=document.createElement('div');d.className='team-row';d.innerHTML=`<i class="team-dot"></i><div><strong>${code} · ${t.name}</strong><small>${t.owner||'Available'} · ${money(t.budget)}</small></div>`;d.onclick=()=>chooseTeam(code);box.appendChild(d)});$('playerCount').textContent=`${Object.values(state.teams).filter(t=>t.owner).length}/8`;renderMine()}
function renderMine(){const t=state.team&&state.teams[state.team];$('myTeamCard').innerHTML=t?`<div class="my-team-card"><b>${state.team} · ${t.name}</b><div class="budget">${money(t.budget)}</div><div class="mini-stats"><span>${t.players.length} players</span><span>${Math.max(0,11-t.players.length)} slots left</span></div></div>`:'<p style="color:var(--muted);font-size:12px">Pick a franchise from the list.</p>'}
function chooseTeam(code){if(state.teams[code].owner&&state.teams[code].owner!==state.name){toast('That franchise is already taken');return}if(state.team)state.teams[state.team].owner=null;state.team=code;state.teams[code].owner=state.name;renderTeams();broadcast({type:'teams',teams:state.teams})}
function renderPlayers(){const q=$('playerSearch').value.toLowerCase(),sf=$('statusFilter').value,rf=$('roleFilter').value;const list=PLAYERS.filter(p=>(!q||p.name.toLowerCase().includes(q)||p.country.toLowerCase().includes(q))&&(sf==='all'||p.status===sf)&&(rf==='all'||p.role===rf));$('playerPool').innerHTML=`<div class="player-list">${list.map(p=>`<div class="player-item"><div><strong>${p.name}</strong><small>${p.country} · ${p.role} · ${p.status==='retired'?'Legend':'Current'} · Base ${money(p.base)}</small></div><span class="add-player">${state.players[p.id]?'SOLD':'IN POOL'}</span></div>`).join('')}</div>`}
function openGame(){ $('lobby').classList.add('hidden');$('game').classList.remove('hidden');$('roomTitle').textContent=state.isHost?'Your Auction Room':'Joined Auction Room';$('connectionPill').className='status-pill online';$('connectionPill').innerHTML='<span></span>Live';renderTeams();renderPlayers();if(state.isHost)setTimeout(startAuction,1800)}
function updateBidButtons(){const box=$('bidButtons');if(!state.current){box.innerHTML='';return}const locked=state.current.lastBidder===state.name;const t=state.team?state.teams[state.team]:null;const increments=[.25,.5,1,2,5];box.innerHTML=increments.map(x=>{const disabled=locked||!t||t.budget<Number(state.current.bid||state.current.base)+x;return `<button class="bid-btn" ${disabled?'disabled':''} onclick="bid(${x})">${locked?'WAIT':'+ '+x.toFixed(2)+' Cr'}</button>`}).join('');box.title=locked?'You already bid. Wait for another franchise.':''}
function setStage(p,lot,autoStart=false){state.current={...p,bid:p.base,leading:null,lastBidder:null};state.lot=lot;$('lotLabel').textContent=`LOT ${String(lot).padStart(3,'0')}`;$('auctionStatus').textContent='ON THE BLOCK';$('playerStage').className='player-stage active';$('playerStage').innerHTML=`<div class="player-avatar">${p.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div class="player-tag">${p.country} · ${p.role} · ${p.status==='retired'?'IPL LEGEND':'CURRENT PLAYER'}</div><h2>${p.name}</h2><p>Base price ${money(p.base)} · <b>BID TO WIN</b></p>`;$('currentBid').textContent=money(p.base);$('leadingTeam').textContent='—';$('timer').textContent='30s';updateBidButtons();$('sellBtn').classList.toggle('hidden',!state.isHost);$('unsoldBtn').classList.toggle('hidden',!state.isHost);log(`<b>${p.name}</b> is now on the block`);if(autoStart)startTimer(true)}
function bid(inc){if(!state.current){toast('No player is on the block');return}if(!state.team){toast('Choose a franchise first');return}if(state.current.lastBidder===state.name){toast('You already bid — wait for another franchise');return}const t=state.teams[state.team];const next=Number(state.current.bid||state.current.base)+inc;if(next>t.budget){toast('Not enough budget');return}state.current.bid=next;state.current.leading=state.team;state.current.lastBidder=state.name;$('currentBid').textContent=money(next);$('leadingTeam').textContent=state.team;updateBidButtons();log(`<b>${state.name}</b> bid ${money(next)} for ${state.current.name}`);broadcast({type:'bid',bid:next,team:state.team,name:state.name})}
function startTimer(silent=false){if(!state.current)return;state.timeLeft=30;clearInterval(state.timer);$('sellBtn').classList.remove('hidden');$('unsoldBtn').classList.remove('hidden');$('auctionStatus').textContent='BIDDING LIVE';state.timer=setInterval(()=>{state.timeLeft--;$('timer').textContent=state.timeLeft+'s';if(state.timeLeft<=0){clearInterval(state.timer);if(state.isHost)sell()}},1000);if(!silent)broadcast({type:'timer'})}
function sell(){if(!state.current||!state.isHost)return;clearInterval(state.timer);const p=state.current,team=p.leading,bid=Number(p.bid||p.base);if(team&&state.teams[team]&&state.teams[team].budget>=bid){const t=state.teams[team];t.budget-=bid;t.players.push(p);state.players[p.id]={...p,soldTo:team,soldFor:bid};log(`<b>${p.name}</b> SOLD to <b>${team}</b> for ${money(bid)}`)}else log(`<b>${p.name}</b> went UNSOLD`);broadcast({type:'sold',player:p,team,bid,teams:state.teams,players:state.players});state.current=null;setTimeout(nextPlayer,1000)}
function unsold(){if(!state.current||!state.isHost)return;clearInterval(state.timer);log(`<b>${state.current.name}</b> went UNSOLD`);broadcast({type:'sold',player:state.current,team:null,bid:0,teams:state.teams,players:state.players});state.current=null;setTimeout(nextPlayer,800)}
function nextPlayer(){if(!state.isHost)return;while(state.queueIndex<state.queue.length&&state.players[state.queue[state.queueIndex].id])state.queueIndex++;if(state.queueIndex>=state.queue.length){finishAuction();return}const p=state.queue[state.queueIndex++];setStage(p,state.lot+1,true);broadcast({type:'stage',player:p,lot:state.lot})}
function startAuction(){if(!state.isHost||state.current)return;state.queue=[...PLAYERS].sort(()=>Math.random()-.5);state.queueIndex=0;state.players={};log('<b>Auction started!</b> Players will appear automatically.');nextPlayer()}
function finishAuction(){clearInterval(state.timer);$('auctionStatus').textContent='AUCTION COMPLETE';$('playerStage').className='player-stage active';$('playerStage').innerHTML='<div class="stage-ball">🏆</div><h2>Auction complete!</h2><p>Check every franchise squad and budget.</p>';$('bidButtons').innerHTML='';$('sellBtn').classList.add('hidden');$('unsoldBtn').classList.add('hidden');broadcast({type:'finish',teams:state.teams,players:state.players})}
function resetStage(){if(!state.current){$('auctionStatus').textContent='NEXT LOT LOADING';$('timer').textContent='—';$('currentBid').textContent='₹0.00 Cr';$('leadingTeam').textContent='—';$('bidButtons').innerHTML='';renderTeams();renderPlayers()}}
function broadcast(msg){state.connections.forEach(c=>{try{if(c.open)c.send(msg)}catch{}})}
function handle(msg){if(msg.type==='teams'){state.teams=msg.teams;renderTeams()}if(msg.type==='stage'){setStage(msg.player,msg.lot,false);startTimerLocal()}if(msg.type==='bid'&&state.current){state.current.bid=msg.bid;state.current.leading=msg.team;state.current.lastBidder=msg.name;$('currentBid').textContent=money(msg.bid);$('leadingTeam').textContent=msg.team;updateBidButtons();log(`<b>${msg.name}</b> bid ${money(msg.bid)} for ${state.current.name}`)}if(msg.type==='timer')startTimerLocal();if(msg.type==='sold'){state.teams=msg.teams;state.players=msg.players;log(msg.team?`<b>${msg.player.name}</b> SOLD to <b>${msg.team}</b> for ${money(msg.bid)}`:`<b>${msg.player.name}</b> went UNSOLD`);state.current=null;resetStage()}if(msg.type==='finish'){state.teams=msg.teams;state.players=msg.players;finishAuction()}if(msg.type==='chat')addChat(msg.name,msg.text)}
function startTimerLocal(){clearInterval(state.timer);state.timeLeft=30;$('auctionStatus').textContent='BIDDING LIVE';$('sellBtn').classList.add('hidden');$('unsoldBtn').classList.add('hidden');state.timer=setInterval(()=>{$('timer').textContent=(--state.timeLeft)+'s';if(state.timeLeft<=0)clearInterval(state.timer)},1000)}
function addChat(n,t){const d=document.createElement('div');d.className='chat-msg';d.innerHTML=`<b>${n}</b> <span>${t.replaceAll('<','&lt;')}</span>`;$('chatMessages').appendChild(d);$('chatMessages').scrollTop=99999}
function host(){state.name=$('hostName').value.trim()||'Host';state.isHost=true;makeTeams();state.room=Math.random().toString(36).slice(2,8).toUpperCase();state.peer=new Peer('ipl-auction-'+state.room);state.peer.on('open',()=>{$('copyRoom').textContent=state.room;toast('Room created: '+state.room);openGame()});state.peer.on('connection',c=>{state.connections.push(c);c.on('data',handle);c.on('open',()=>{c.send({type:'teams',teams:state.teams});toast('Friend joined the auction')})});state.peer.on('error',e=>toast('Peer error: '+e.type))}
function join(){state.name=$('guestName').value.trim()||'Player';state.room=$('roomCode').value.trim().toUpperCase();if(!state.room)return toast('Enter a room code');state.isHost=false;makeTeams();state.peer=new Peer();state.peer.on('open',()=>{const c=state.peer.connect('ipl-auction-'+state.room);state.connections=[c];c.on('open',()=>{openGame();c.send({type:'chat',name:'SYSTEM',text:`${state.name} joined the auction`})});c.on('data',handle);c.on('error',()=>toast('Could not join room'))});state.peer.on('error',()=>toast('Could not connect to room'))}
$('createRoom').onclick=host;$('joinRoom').onclick=join;$('playerSearch').oninput=renderPlayers;$('statusFilter').onchange=renderPlayers;$('roleFilter').onchange=renderPlayers;$('sellBtn').onclick=sell;$('unsoldBtn').onclick=unsold;$('copyRoom').onclick=()=>navigator.clipboard?.writeText(state.room).then(()=>toast('Room code copied'));$('copyInvite').onclick=()=>navigator.clipboard?.writeText(location.href+'?room='+state.room).then(()=>toast('Invite copied'));$('leaveRoom').onclick=()=>location.reload();$('chatForm').onsubmit=e=>{e.preventDefault();const t=$('chatInput').value.trim();if(!t)return;addChat(state.name,t);broadcast({type:'chat',name:state.name,text:t});$('chatInput').value=''};window.bid=bid;renderPlayers();
