const TEAM_NAMES=['Mumbai Indians','Chennai Super Kings','Royal Challengers Bengaluru','Kolkata Knight Riders','Rajasthan Royals','Sunrisers Hyderabad','Delhi Capitals','Punjab Kings'];
const TEAM_CODES=['MI','CSK','RCB','KKR','RR','SRH','DC','PBKS'];
const state={room:null,isHost:false,name:'',team:null,peer:null,connections:[],players:{},teams:{},current:null,lot:0,timer:null,timeLeft:30};
const $=id=>document.getElementById(id); const money=n=>`₹${Number(n).toFixed(2)} Cr`;
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2200)}
function log(t){const d=document.createElement('div');d.className='log-item';d.innerHTML=t;$('activityLog').prepend(d)}
function makeTeams(){state.teams={};TEAM_NAMES.forEach((name,i)=>state.teams[TEAM_CODES[i]]={name,owner:null,budget:100,players:[]})}
function renderTeams(){const box=$('teamsList');box.innerHTML='';Object.entries(state.teams).forEach(([code,t])=>{const d=document.createElement('div');d.className='team-row';d.innerHTML=`<i class="team-dot"></i><div><strong>${code} · ${t.name}</strong><small>${t.owner||'Available'} · ${money(t.budget)}</small></div>`;d.onclick=()=>chooseTeam(code);box.appendChild(d)});$('playerCount').textContent=`${Object.values(state.teams).filter(t=>t.owner).length}/8`;renderMine()}
function renderMine(){const t=state.team&&state.teams[state.team];$('myTeamCard').innerHTML=t?`<div class="my-team-card"><b>${state.team} · ${t.name}</b><div class="budget">${money(t.budget)}</div><div class="mini-stats"><span>${t.players.length} players</span><span>${Math.max(0,11-t.players.length)} slots left</span></div></div>`:'<p style="color:var(--muted);font-size:12px">Pick a franchise from the list.</p>'}
function chooseTeam(code){if(state.teams[code].owner&&state.teams[code].owner!==state.name){toast('That franchise is already taken');return} if(state.team)state.teams[state.team].owner=null;state.team=code;state.teams[code].owner=state.name;renderTeams();broadcast({type:'teams',teams:state.teams});toast(`You selected ${code}`)}
function renderPlayers(){const q=$('playerSearch').value.toLowerCase(),sf=$('statusFilter').value,rf=$('roleFilter').value;const list=PLAYERS.filter(p=>(!q||p.name.toLowerCase().includes(q)||p.country.toLowerCase().includes(q))&&(sf==='all'||p.status===sf)&&(rf==='all'||p.role===rf));$('playerPool').innerHTML=`<div class="player-list">${list.map(p=>`<div class="player-item"><div><strong>${p.name}</strong><small>${p.country} · ${p.role} · ${p.status==='retired'?'Legend':'Current'} · Base ${money(p.base)}</small></div><button class="add-player" onclick="nominate('${p.id}')">${state.isHost?'Nominate':'View'}</button></div>`).join('')}</div>`}
function openGame(){ $('lobby').classList.add('hidden');$('game').classList.remove('hidden');$('roomTitle').textContent=state.isHost?'Your Auction Room':'Joined Auction Room';$('connectionPill').className='status-pill online';$('connectionPill').innerHTML='<span></span>Live';renderTeams();renderPlayers();updateHostUI()}
function updateHostUI(){document.querySelectorAll('.host-only').forEach(x=>x.classList.toggle('hidden',!state.isHost));if(!state.isHost){$('startTimerBtn').classList.add('hidden');$('sellBtn').classList.add('hidden');$('unsoldBtn').classList.add('hidden')}}
function stage(p){state.current=p;state.timeLeft=30;$('lotLabel').textContent=`LOT ${String(++state.lot).padStart(3,'0')}`;$('auctionStatus').textContent='ON THE BLOCK';$('playerStage').className='player-stage active';$('playerStage').innerHTML=`<div class="player-avatar">${p.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div class="player-tag">${p.country} · ${p.role} · ${p.status==='retired'?'IPL LEGEND':'CURRENT PLAYER'}</div><h2>${p.name}</h2><p>Base price ${money(p.base)}</p>`;$('currentBid').textContent=money(p.base);$('leadingTeam').textContent='—';$('timer').textContent='30s';$('bidButtons').innerHTML=[.25,.5,1,2,5].map(x=>`<button class="bid-btn" onclick="bid(${x})">+${x.toFixed(2)} Cr</button>`).join('');$('startTimerBtn').classList.remove('hidden');$('sellBtn').classList.add('hidden');$('unsoldBtn').classList.add('hidden');log(`<b>${p.name}</b> is on the block · base ${money(p.base)}`);broadcast({type:'stage',player:p,lot:state.lot})}
function nominate(id){if(!state.isHost){toast('Only the auctioneer can nominate');return}const p=PLAYERS.find(x=>x.id===id);if(!p||state.players[p.id]){toast('Player already sold');return}stage(p)}
function bid(inc){if(!state.current){toast('No player on the block');return}if(!state.team){toast('Pick a franchise first');return}const t=state.teams[state.team],old=Number($('currentBid').textContent.replace(/[^0-9.]/g,''))||state.current.base;const next=old+inc;if(next>t.budget){toast('Not enough budget');return}state.current.bid=next;state.current.leading=state.team;$('currentBid').textContent=money(next);$('leadingTeam').textContent=state.team;log(`<b>${state.name}</b> bid ${money(next)} for ${state.current.name}`);broadcast({type:'bid',bid:next,team:state.team,name:state.name})}
function startTimer(){if(!state.current)return;state.timeLeft=30;$('startTimerBtn').classList.add('hidden');$('sellBtn').classList.remove('hidden');$('unsoldBtn').classList.remove('hidden');clearInterval(state.timer);state.timer=setInterval(()=>{state.timeLeft--;$('timer').textContent=state.timeLeft+'s';if(state.timeLeft<=0){clearInterval(state.timer);sell() }},1000);broadcast({type:'timer',running:true})}
function sell(){if(!state.current)return;clearInterval(state.timer);const p=state.current,team=state.current.leading,bid=Number(state.current.bid||p.base);if(team&&state.teams[team]){const t=state.teams[team];if(t.budget>=bid){t.budget-=bid;t.players.push(p);state.players[p.id]={...p,soldTo:team,soldFor:bid};log(`<b>${p.name}</b> SOLD to <b>${team}</b> for ${money(bid)}`)}}else log(`<b>${p.name}</b> went UNSOLD`);broadcast({type:'sold',player:p,team,bid,teams:state.teams,players:state.players});state.current=null;setTimeout(()=>resetStage(),700)}
function unsold(){if(!state.current)return;clearInterval(state.timer);log(`<b>${state.current.name}</b> went UNSOLD`);broadcast({type:'sold',player:state.current,team:null,bid:0,teams:state.teams,players:state.players});state.current=null;resetStage()}
function resetStage(){$('auctionStatus').textContent='WAITING';$('timer').textContent='—';$('currentBid').textContent='₹0.00 Cr';$('leadingTeam').textContent='—';$('bidButtons').innerHTML='';$('playerStage').className='player-stage empty';$('playerStage').innerHTML='<div class="stage-ball">🏏</div><h2>Ready for the next nomination?</h2><p>Host can select a player from the pool.</p>';renderTeams();renderPlayers()}
function broadcast(msg){state.connections.forEach(c=>{try{c.send(msg)}catch{}})}
function handle(msg){if(msg.type==='teams'){state.teams=msg.teams;renderTeams()}if(msg.type==='stage'){state.current=msg.player;state.lot=msg.lot-1;stageLocal(msg.player,msg.lot)}if(msg.type==='bid'){$('currentBid').textContent=money(msg.bid);$('leadingTeam').textContent=msg.team;log(`<b>${msg.name}</b> bid ${money(msg.bid)} for ${state.current?.name||'player'}`)}if(msg.type==='timer'){startTimerLocal()}if(msg.type==='sold'){state.teams=msg.teams;state.players=msg.players;log(msg.team?`<b>${msg.player.name}</b> SOLD to <b>${msg.team}</b> for ${money(msg.bid)}`:`<b>${msg.player.name}</b> went UNSOLD`);resetStage() }if(msg.type==='chat'){addChat(msg.name,msg.text)}}
function stageLocal(p,lot){state.current=p;$('lotLabel').textContent=`LOT ${String(lot).padStart(3,'0')}`;$('auctionStatus').textContent='ON THE BLOCK';$('playerStage').className='player-stage active';$('playerStage').innerHTML=`<div class="player-avatar">${p.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div class="player-tag">${p.country} · ${p.role} · ${p.status==='retired'?'IPL LEGEND':'CURRENT PLAYER'}</div><h2>${p.name}</h2><p>Base price ${money(p.base)}</p>`;$('currentBid').textContent=money(p.base);$('leadingTeam').textContent='—';$('timer').textContent='30s';$('bidButtons').innerHTML=[.25,.5,1,2,5].map(x=>`<button class="bid-btn" onclick="bid(${x})">+${x.toFixed(2)} Cr</button>`).join('')}
function startTimerLocal(){clearInterval(state.timer);state.timeLeft=30;state.timer=setInterval(()=>{$('timer').textContent=(--state.timeLeft)+'s';if(state.timeLeft<=0)clearInterval(state.timer)},1000)}
function addChat(n,t){const d=document.createElement('div');d.className='chat-msg';d.innerHTML=`<b>${n}</b> <span>${t.replaceAll('<','&lt;')}</span>`;$('chatMessages').appendChild(d);$('chatMessages').scrollTop=99999}
function host(){state.name=$('hostName').value.trim()||'Host';state.isHost=true;makeTeams();state.room=Math.random().toString(36).slice(2,8).toUpperCase();const peerId='ipl-auction-'+state.room;state.peer=new Peer(peerId);state.peer.on('open',()=>{$('copyRoom').textContent=state.room;toast('Room created: '+state.room);openGame()});state.peer.on('connection',c=>{state.connections.push(c);c.on('data',handle);c.on('open',()=>{c.send({type:'teams',teams:state.teams});toast('A friend joined the room')})});state.peer.on('error',e=>toast('Peer error: '+e.type))}
function join(){state.name=$('guestName').value.trim()||'Player';state.room=$('roomCode').value.trim().toUpperCase();if(!state.room)return toast('Enter a room code');state.isHost=false;makeTeams();state.peer=new Peer();state.peer.on('open',()=>{const c=state.peer.connect('ipl-auction-'+state.room);state.connections=[c];c.on('open',()=>{openGame();c.send({type:'chat',name:'SYSTEM',text:`${state.name} joined the auction`})});c.on('data',handle);c.on('error',()=>toast('Could not join room'))});state.peer.on('error',()=>toast('Could not connect to room'))}
$('createRoom').onclick=host;$('joinRoom').onclick=join;$('playerSearch').oninput=renderPlayers;$('statusFilter').onchange=renderPlayers;$('roleFilter').onchange=renderPlayers;$('nominateBtn').onclick=()=>toast('Choose a player from the pool');$('startTimerBtn').onclick=startTimer;$('sellBtn').onclick=sell;$('unsoldBtn').onclick=unsold;$('copyRoom').onclick=()=>navigator.clipboard?.writeText(state.room).then(()=>toast('Room code copied'));$('copyInvite').onclick=()=>navigator.clipboard?.writeText(location.href+'?room='+state.room).then(()=>toast('Invite copied'));$('leaveRoom').onclick=()=>location.reload();$('chatForm').onsubmit=e=>{e.preventDefault();const t=$('chatInput').value.trim();if(!t)return;addChat(state.name,t);broadcast({type:'chat',name:state.name,text:t});$('chatInput').value=''};window.nominate=nominate;window.bid=bid;
renderPlayers();
